Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 200

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/ParameterAlignment:
  Enabled: false
